run:
  skip-dirs:
    - test/includes
  skip-files:
    - pkg/parser/parser.go # generated
  timeout: 5m
  
linters:
  enable-all: false
  enable:
    - megacheck
    - govet
    - gocyclo
    - unused
    - gofmt
    - revive
    - misspell
    - exportloopref
  disable-all: false
  disable:
    - maligned
    - prealloc
    - scopelint
  presets:
    - bugs
    - unused
  fast: false

linters-settings:
  exhaustive:
    # check switch statements in generated files also
    check-generated: false
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true