run:
  skip-dirs:
    - test/includes
  skip-files:
    - pkg/parser/parser.go # generated

linters:
  enable:
    - megacheck
    - govet
    - gocyclo
    - unused
    - gofmt
    - golint
    - misspell
  enable-all: false
  disable:
    - maligned
    - prealloc
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false
