# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
-
  # Path to main.go file or main package.
  # Default is `.`.
  main: ./cmd/libasciidoc
  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
  ldflags:
    - "-s -w -X github.com/bytesparadise/libasciidoc.BuildTag={{.Version}} -X github.com/bytesparadise/libasciidoc.BuildCommit={{.Commit}} -X github.com/bytesparadise/libasciidoc.BuildTime={{.Date}}"
  env:
    - CGO_ENABLED=0

archives:
  - id: default
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)(/(\\w))?]*:+.*$"
      order: 0
    - title: Refactoring
      regexp: "^.*refactor[(\\w)(/(\\w))?]*:+.*$"
      order: 1
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)(/(\\w))?]*:+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
    - '^docs:'
    - '^test:'
