dist: trusty
sudo: false

language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - tip

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git config --global core.autocrlf true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make; fi
  - make install-devtools
  - make deps

script:
  # verify that the commit code for the parser was optimized during the code generation
  - make verify-parser
  # verify that the library builds completely
  - make build
  # run the tests
  - export CI=travis-ci
  - make test

after_success:
  - gover . coverage.txt
  - bash <(curl -s https://codecov.io/bash)
