dist: trusty
sudo: false

language: go

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - tip

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on
  
matrix:
  fast_finish: true
  allow_failures:
  - go: tip

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git config --global core.autocrlf true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make --version 4.3; fi
  - make install-devtools

script:
  # verify that the commit code for the parser was optimized during the code generation
  - make verify-parser
  # verify that the library builds completely
  - export CI=travis-ci
  - make build
  # run the tests
  - make test-with-coverage

after_success:
  - gover . coverage.txt
  - bash <(curl -s https://codecov.io/bash)
