= Known limitations and differences with Asciidoc/Asciidoctor

This document reports the known limitations and differences with Asciidoc/Asciidoctor.
In any case, feel free to https://github.com/bytesparadise/libasciidoc/issues[open an issue]
if you want to discuss an actual limitation of Libasciidoc or if you want to report a new one.
We also accept pull requests.

This list is not necessarily complete, but it should reflect the differences
likely to impact real documents.
The entire list of known issues is tracked in https://github.com/bytesparadise/libasciidoc/issues[GitHub].
We plan to address the majority of these issues.

== Two-line Section Titles

Two-line section titles (setext headings) are not supported, and there are no plans to support it for now.
See https://github.com/bytesparadise/libasciidoc/issues/187[Issue #187] for more on this decision.

== Passthroughs

The Inline pass macro will not render nothing at all instead of an empty paragraph
when the macro is empty. I.e.:

....
pass:[]
....

will produce no HTML element at all, whereas Asciidoc/Asciidoctor will produce :

....
<div class="paragraph">
<p></p>
</div>
....

== Constrained Monospace Text and Quoted Strings or Apostrophes

Constrained or imbalanced monospace text may not act fully constrained, or may be confused in the presence of
imbalanced quoted strings or apostrophes.  Typically such markup is erroneous, but the results from such errors may
differ between implementations.
See https://github.com/bytesparadise/libasciidoc/issues/630[Issue #630].

== Attribute Lists

Attributes containing inline markup are not rendered with the markup applied.

Attributes lists using undocumented whitespace (particularly in positional parameters) may not parse correctly.
(Use single or double quotes if your attribute values contain leading or trailing whitespace, and avoid the use
of whitespace between or surrounding attributes for the most consistent results.)

Escaping of quotes within quoted strings used as attribute value does not work.

== Tables

Custom table delimiters, and custom formats (TSV, CSV, DSV) are not supported.
See https://github.com/bytesparadise/libasciidoc/issues/696[Issue #696].

Tables will not parse if the content starts with a blank line.
See https://github.com/bytesparadise/libasciidoc/issues/692[Issue #692].

Individual cell styles, including spans and repeats, are not supported.
See https://github.com/bytesparadise/libasciidoc/issues/695[Issue #695].

The style attribute for cell contents (specified in the cols attribute) is ignored (the "d" style for inline content is assumed).
See https://github.com/bytesparadise/libasciidoc/issues/694[Issue #694].

The parser will likely be confused by ragged tables, or tables that do not use one line per row.
See https://github.com/bytesparadise/libasciidoc/issues/637[Issue #637].

No support for nested tables. See https://github.com/bytesparadise/libasciidoc/issues/697[Issue #697].

== Lists

Interactive checklists are not supported.
See https://github.com/bytesparadise/libasciidoc/issues/675[Issue #675].

== Images

Interactive SVG support is missing, as is support for inline SVG.
See https://github.com/bytesparadise/libasciidoc/issues/674[Issue #674].

The global figure-caption attribute is not honored.
Use per-image caption attributes for more control if needed.

== Multimedia

Video and audio elements are not supported.
See https://github.com/bytesparadise/libasciidoc/issues/677[Issue #677].

== File Inclusions

File inclusions are performed before the full parsing takes place. During this phase, the main file is parsed to look for `include::` directives and then replace them with the content of the file to include. 
If the file to include has an empty last line, it will be ignored, so it's always a good practice to include a blank line after the `include::` directive in the main document, to avoid side-effects during
the "full" parsing.

== Symbols and Characters

Markup for the mdash and arrow symbols is not recognized.
See https://github.com/bytesparadise/libasciidoc/issues/678[Issue #678].

Symbols for quotes (both single and double) will be inlined as numeric HTML entities, even in cases where this is not strictly necessary.

Symbolic entity names (such as `&loz;` for &loz;) are not recognized -- leaving recognition and rendering dependent on the user-agent.
See https://github.com/bytesparadise/libasciidoc/issues/680[Issue #680].

== User Interface Macros

The experimental macros for user interfaces (`kbd`, `menu`, and `btn`) are not supported.
See https://github.com/bytesparadise/libasciidoc/issues/607[Issue #607].

== Admonitions

Use of unicode symbols or other replacement using the per-type caption attribute is not supported.
See https://github.com/bytesparadise/libasciidoc/issues/679[Issue #679].

== Favicon

The `favicon` document attribute is not recognized.
See https://github.com/bytesparadise/libasciidoc/issues/681[Issue #681].

== Syntax Highlighters

Only the `pygments` highlighter is recognized.

== Math

MathML and equations (`[stem]` blocks) are not supported yet.
See https://github.com/bytesparadise/libasciidoc/issues/608[Issue #608].

== Bibliographies

Bibliographies using bibtex are not supported yet.
See https://github.com/bytesparadise/libasciidoc/issues/609[Issue #609].

== Links

When using the `*` and `_` characters at the end of URLs of external links in a quoted text, the attributes markers need to be explicitly set. Eg: `+++a link to *https://foo.com/_[]*+++`.

Using the caret short-hand to indicate link targets should use the blank window is not support.
See https://github.com/bytesparadise/libasciidoc/issues/682[Issue #682].

== Document Types

The inline and book document types are not supported.  Article and manpage documents work fine.
See https://github.com/bytesparadise/libasciidoc/issues/628[Issue #628] and
https://github.com/bytesparadise/libasciidoc/issues/629[Issue #629].

== CSS

At present no CSS is provided, but the output generated should be compatible with asciidoctor CSS.
See https://github.com/bytesparadise/libasciidoc/issues/63[Issue #63].

== Output Formats (Back-ends)

Only HTML and XHTML backends are supported.

== CLI

Support for -d to set the document type is missing.
See https://github.com/bytesparadise/libasciidoc/issues/616[Issue #616].

