= Known limitations and differences with Asciidoc/Asciidoctor

This document reports the known limitations and differences with Asciidoc/Asciidoctor.
In any case, feel free to https://github.com/bytesparadise/libasciidoc/issues[open an issue]
if you want to discuss about an actual limitation of Libasciidoc or if you want to report a new one.

== Quoted Text

Quoted text rendering can differ in the following cases:

- when the punctuation is unbalanced. Eg:
....
some **bold content*.
....
will be rendered as the raw input:
....
some **bold content*.
....
instead of :
....
<p>some <strong>*bold content</strong></p>
....

- when quoted text uses the same punctuation. Eg:
....
*some *nested bold* content*.
....
Libasciidoc will detect the nested bold quote and renderer accordingly:
....
<strong>some <strong>nested bold</strong> content</strong>.
....
whereas Asciidoc/Asciidoctor will produce :
....
<p><strong>some *nested bold</strong> content*.</p>
....

== Two-line Section Titles

Two-line section titles (setext headings) are not supported, and there are no plans to support it for now.
See https://github.com/bytesparadise/libasciidoc/issues/187[Issue #187] for more on this decision.

== Passthroughs

The Inline pass macro will not render nothing at all instead of an empty paragraph
when the macro is empty. I.e.:

....
pass:[]
....

will produce no HTML element at all, whereas Asciidoc/Asciidoctor will produce :

....
<div class="paragraph">
<p></p>
</div>
....

== File Inclusions

File inclusions are performed before the full parsing takes place. During this phase, the main file is parsed to look for `include::` directives and then replace them with the content of the file to include. 
If the file to include has an empty last line, it will be ignored, so it's always a good practice to include a blank line after the `include::` directive in the main document, to avoid side-effects during
the "full" parsing.

== Links

When using the `*` and `_` characters at the end of URLs of external links in a quoted text, the attributes markers need to be explicitly set. Eg: `+++a link to *https://foo.com/_[]*+++`.