package sgml

// Templates represents all the templates we use.
type Templates struct {
	AdmonitionBlock           string
	AdmonitionParagraph       string
	Article                   string
	ArticleHeader             string
	BlankLine                 string
	BlockImage                string
	BoldText                  string
	CalloutList               string
	CalloutListItem           string
	DelimitedBlockParagraph   string
	DocumentDetails           string
	DocumentAuthorDetails     string
	ExampleBlock              string
	ExternalCrossReference    string
	FencedBlock               string
	Footnote                  string
	FootnoteItem              string
	FootnoteRef               string
	FootnoteRefPlain          string
	Footnotes                 string
	IconFont                  string
	IconImage                 string
	IconText                  string
	ImageCaption              string
	InlineIcon                string
	InlineImage               string
	InternalCrossReference    string
	InvalidFootnote           string
	ItalicText                string
	LabeledList               string
	LabeledListItem           string
	LabeledListHorizontal     string
	LabeledListHorizontalItem string
	LineBreak                 string
	Link                      string
	ListingBlock              string
	LiteralBlock              string
	ManpageHeader             string
	ManpageNameParagraph      string
	MarkedText                string
	MonospaceText             string
	OrderedList               string
	OrderedListItem           string
	Paragraph                 string
	PassthroughBlock          string
	Preamble                  string
	QAndAList                 string
	QAndAListItem             string
	QuoteBlock                string
	QuoteParagraph            string
	SectionContent            string
	SectionHeader             string
	SidebarBlock              string
	SourceBlock               string
	StringElement             string
	SubscriptText             string
	SuperscriptText           string
	Table                     string
	TableBody                 string
	TableCaption              string
	TableCell                 string
	TableHeader               string
	TableHeaderCell           string
	TableRow                  string
	ThematicBreak             string
	TocEntry                  string
	TocRoot                   string
	TocSection                string
	UnorderedList             string
	UnorderedListItem         string
	VerbatimLine              string
	VerseBlock                string
	VerseParagraph            string
}
