package sgml

// Templates represents all the templates we use.
// go:generate
type Templates struct {
	AdmonitionBlock              string
	AdmonitionParagraph          string
	Article                      string
	ArticleHeader                string
	BlockImage                   string
	BoldText                     string
	CalloutList                  string
	CalloutListElement           string
	CalloutRef                   string
	EmbeddedParagraph            string
	DocumentDetails              string
	DocumentAuthorDetails        string
	ExampleBlock                 string
	ExternalCrossReference       string
	FencedBlock                  string
	Footnote                     string
	FootnoteElement              string
	FootnoteRef                  string
	Footnotes                    string
	IconFont                     string
	IconImage                    string
	IconText                     string
	InlineButton                 string
	InlineIcon                   string
	InlineImage                  string
	InlineMenu                   string
	InternalCrossReference       string
	InvalidFootnote              string
	ItalicText                   string
	LabeledList                  string
	LabeledListElement           string
	LabeledListHorizontal        string
	LabeledListHorizontalElement string
	LineBreak                    string
	Link                         string
	ListingBlock                 string
	LiteralBlock                 string
	ManpageHeader                string
	ManpageNameParagraph         string
	MarkdownQuoteBlock           string
	MarkedText                   string
	MonospaceText                string
	OpenBlock                    string
	OrderedList                  string
	OrderedListElement           string
	Paragraph                    string
	PassthroughBlock             string
	Preamble                     string
	QAndAList                    string
	QAndAListElement             string
	QuoteBlock                   string
	QuoteParagraph               string
	SectionContent               string
	SectionTitle                 string
	SidebarBlock                 string
	SourceBlock                  string
	SubscriptText                string
	SuperscriptText              string
	Table                        string
	TableBody                    string
	TableCell                    string
	TableCellBlock               string
	TableHeader                  string
	TableHeaderCell              string
	TableFooter                  string
	TableFooterCell              string
	TableRow                     string
	ThematicBreak                string
	TocEntry                     string
	TocRoot                      string
	TocSection                   string
	UnorderedList                string
	UnorderedListElement         string
	VerseBlock                   string
	VerseParagraph               string
}
