= Libasciidoc Design

This document brifley explains how the library works, from parsing a document to rendering in HTML.

== Types

A document contains blocks, which can have attributes, nested blocks and elements.

Blocks are of the following types:

- Section
- Paragraph
- Delimited block
- Image
- Table
- List
- File inclusion
- Comment

Tables, lists and delimited blocks can contain other blocks.

Blocks can also contain elements, such as:

- quoted text
- links
- (inline) images
- passthrough text
- foot notes
- user-defined macros

Attributes are set within squate brackets (`[]`), both on top of the document blocks and as a suffix of elements.


== Parsing the document

First, the internal parser (generated after the link:../pkg/parser/parser.peg[grammar] returns a "draft document" in which the sections are not embedded in a hierarchical manner, other blocks are also not attached to their parent section, blanklines are present, document attributes declarations, substitutions and reset macros are also present, and file inclusions have been processed. 

This so-called "draft document" is then processed to return a "final document" in which the sections are organized in a hierarchical manner with their child blocks (paragraphs, delimited blocks, etc.) attached to them. Also, all document attribute substitutions have been processed (sometimes resulting in new elements such as links) and removed. Blank line elements have been stripped off, too (except in delimited blocks).

== HTMl5 Rendering

The HTML5 renderer takes the final document and applies templates for each element. Having the sections in a hierarchical manner makes life easier in term of surrounding `<div>` tags.