name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Test ${{ matrix.os }} with Go ${{ matrix.go-version }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles ('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make test-with-coverage

    - name: Codecov
      if: runner.os == 'Linux'
      uses: codecov/codecov-action@v1.0.6
      with:
        # Path to coverage file to upload
        file: coverage.txt

    - name: Smoke Test Benchmarks
      if: runner.os == 'Linux'
      run: |
        make bench-smoke

  golangci:
    name: Lint with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
        args: -E gofmt,golint,megacheck,misspell

