name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master


jobs:
  
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: Building on ${{ matrix.platform }} with Go ${{ matrix.go }}
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Install Tools
      run: 
        make install-devtools
      
    - name: Build on Linux/macOS
      if: runner.os == 'Linux' || runner.os == 'Windows'
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make build
      
    - name: Build on Windows
      if: runner.os == 'Windows'
      run: |
        set PATH=%PATH%;$(go env GOPATH)\bin
        make build

  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: Testing on ${{ matrix.platform }} with Go ${{ matrix.go }}
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Extra setup for Windows
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf true
        choco install make
    
    - name: Install Tools
      run: 
        make install-devtools
      
    - name: Test on Linux and macOS
      if: runner.os != 'Windows'
      env:
        PATH: $PATH:$(go env GOPATH)/bin
      run: |
        make test-with-coverage

    - name: Test on Windows
      if: runner.os == 'Windows'
      run: |
        set PATH=%PATH%;$(go env GOPATH)\bin
        make test
