name: ci-bench
on:
  pull_request_target:
    branches:
      - master

jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    name: Benchstat with Go ${{ matrix.go-version }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles ('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Verify parser
      run: |
        make verify-parser

    - name: Bench and Diff
      id: bench-diff
      run: |
        go install golang.org/x/perf/cmd/benchstat@latest
        make bench-diff
        DIFF_MASTER=$(make print-bench-diff-master)
        # because set-output doesn't support multiline content out-of-the-box
        DIFF_MASTER="${DIFF_MASTER//'%'/'%25'}"
        DIFF_MASTER="${DIFF_MASTER//$'\n'/'%0A'}"
        DIFF_MASTER="${DIFF_MASTER//$'\r'/'%0D'}"
        echo "::set-output name=diff-master::$DIFF_MASTER"

        DIFF_LATEST_RELEASE=$(make print-bench-diff-latest-release)
        # because set-output doesn't support multiline content out-of-the-box
        DIFF_LATEST_RELEASE="${DIFF_LATEST_RELEASE//'%'/'%25'}"
        DIFF_LATEST_RELEASE="${DIFF_LATEST_RELEASE//$'\n'/'%0A'}"
        DIFF_LATEST_RELEASE="${DIFF_LATEST_RELEASE//$'\r'/'%0D'}"
        echo "::set-output name=diff-latest-release::$DIFF_LATEST_RELEASE"

    - name: Comment Benchmark Diffs
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: bench
        message: |
          Comparing with `master` branch:

          ```
          ${{ steps.bench-diff.outputs.diff-master }}
          ```
          
          Comparing with latest release:
          
          ```
          ${{ steps.bench-diff.outputs.diff-latest-release }}
          ```
          </details>
