name: ci-lint
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
    name: Lint on ${{ matrix.os }} / go ${{ matrix.go-version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2.3.0
      with:
        timeout
        version: latest
        args: -c .golangci.yml

