name: Test
on: [push]
jobs:
  
  build:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
    name: ${{ runner }} with Go ${{ matrix.go }}

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
  
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
          go-version: ${{ matrix.go }}
  
    - name: Install Tools
      run: make install-devtools
      
    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make build
      
    - name: Tests
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make test-with-coverage
